version: '3.8'

services:
  spark-dev:
    # Constrói a imagem a partir do Dockerfile localizado em ./infra
    build:
      context: .
      dockerfile: infra/Dockerfile
    # Nomeia a imagem para referência futura
    image: poc-spark-env
    # Mantém o container rodando e permite interação via terminal (equivale a -it)
    tty: true
    stdin_open: true
    # Mapeia os volumes
    volumes:
      # Mapeia o diretório do projeto para /app dentro do container
      - .:/app
      # Mapeia as credenciais do Kaggle (apenas leitura para maior segurança)
      - ~/.kaggle:/root/.kaggle:ro